/**
 * @link https://imagekit.io/docs/transformations
 */
const supportedTransforms: { [key: string]: string } = {
  aspectRatio: "ar",
  background: "bg",
  border: "b",
  crop: "c",
  cropMode: "cm",
  DPR: "dpr",
  focus: "fo",
  quality: "q",
  x: "x",
  xCenter: "xc",
  y: "y",
  yCenter: "yc",
  height: "h",
  width: "w",
  format: "f",
  videoCodec: "vc",
  audioCodec: "ac",
  radius: "r",
  rotation: "rt",
  rotate: "rt",
  blur: "bl",
  named: "n",
  defaultImage: "di",
  flip: "fl",
  original: "orig",
  startOffset: "so",
  endOffset: "eo",
  duration: "du",
  streamingResolutions: "sr",
  eGrayscale: "e-grayscale",
  eRemoveDotBg: "e-removedotbg",
  eUpscale: "e-upscale",
  eRetouch: "e-retouch",
  eGenvar: "e-genvar",
  eDropshadow: "e-dropshadow",
  eChangeBg: "e-changebg",
  eBgRemove: "e-bgremove",
  eContrast: "e-contrast",
  eShadow: "e-shadow",
  eSharpen: "e-sharpen",
  eUSM: "e-usm",
  eGradient: "e-gradient",
  effectContrast: "e-contrast",
  effectShadow: "e-shadow",
  effectSharpen: "e-sharpen",
  effectUSM: "e-usm",
  effectGradient: "e-gradient",
  effectGray: "e-grayscale",
  progressive: "pr",
  lossless: "lo",
  colorProfile: "cp",
  metadata: "md",
  opacity: "o",
  trim: "t",
  zoom: "z",
  page: "pg",
  raw: "raw",
}


export default supportedTransforms